File Location : /etc/httpd/conf/httpd.conf

# Apache Configuration for Linux Hosting Project

Listen 80
ServerName 192.168.16.144

DocumentRoot "/var/www/html"

<Directory "/var/www/html">
    AllowOverride None
    Require all granted
</Directory>

ErrorLog logs/error_log
CustomLog logs/access_log combined